// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

/*
Package payload is a generated protocol buffer package.

It is generated from these files:
	movie.proto

It has these top-level messages:
	Movie
	Person
*/
package payload

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	Title    string    `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Director *Person   `protobuf:"bytes,2,opt,name=director" json:"director,omitempty"`
	Cast     []*Person `protobuf:"bytes,3,rep,name=cast" json:"cast,omitempty"`
	Release  string    `protobuf:"bytes,4,opt,name=release" json:"release,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetDirector() *Person {
	if m != nil {
		return m.Director
	}
	return nil
}

func (m *Movie) GetCast() []*Person {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *Movie) GetRelease() string {
	if m != nil {
		return m.Release
	}
	return ""
}

type Person struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*Movie)(nil), "payload.Movie")
	proto.RegisterType((*Person)(nil), "payload.Person")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x2f, 0xcb,
	0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c,
	0x51, 0xea, 0x64, 0xe4, 0x62, 0xf5, 0x05, 0x49, 0x08, 0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4,
	0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0xda, 0x5c, 0x1c, 0x29, 0x99,
	0x45, 0xa9, 0xc9, 0x25, 0xf9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xfc, 0x7a, 0x50,
	0xbd, 0x7a, 0x01, 0xa9, 0x45, 0xc5, 0xf9, 0x79, 0x41, 0x70, 0x05, 0x42, 0xca, 0x5c, 0x2c, 0xc9,
	0x89, 0xc5, 0x25, 0x12, 0xcc, 0x0a, 0xcc, 0xd8, 0x14, 0x82, 0x25, 0x85, 0x24, 0xb8, 0xd8, 0x8b,
	0x52, 0x73, 0x52, 0x13, 0x8b, 0x53, 0x25, 0x58, 0xc0, 0x36, 0xc1, 0xb8, 0x4a, 0x2e, 0x5c, 0x6c,
	0x10, 0x95, 0x42, 0xb2, 0x5c, 0x5c, 0x69, 0x99, 0x45, 0xc5, 0x25, 0xf1, 0x79, 0x89, 0xb9, 0x30,
	0x07, 0x71, 0x82, 0x45, 0xfc, 0x12, 0x73, 0x53, 0x85, 0xa4, 0xb9, 0x38, 0x73, 0x12, 0x61, 0xb2,
	0x4c, 0x60, 0x59, 0x0e, 0x90, 0x00, 0x48, 0x32, 0x89, 0x0d, 0xec, 0x43, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x00, 0x1d, 0x67, 0xb5, 0xf0, 0x00, 0x00, 0x00,
}
